---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Resumo

Problemas de dados faltantes em pesquisas são recorrentes, e geram a questão principal de como inferir informações a partir de pesquisas com dados ausentes. Para a resposta dessa pergunta pesquisadores desenvolveram métodos para tratamento de informações faltantes ou não resposta em algumas perguntas. Um dos métodos que foi muito utilizado é o de exclusão da informação ausente, entretanto essa ação pode comprometer as informações das análises proporcionadas pela pesquisa. Outro método criado por Rubin(1987), que está sendo utilizado nesse estudo, chama-se Imputação Múltipla. Em que valores para os dados ausentes são imputados no banco de dados através das informações de outros dados que estão presentes no banco; uma das maiores contribuições desse método é a conservação da informação completa da pesquisa. Nessa pesquisa utilizamos o método de imputação múltipla do banco de dados *ustermlife* retirado do pacote *CASDatasets* do software *R*; o banco de dados é uma amostra de 500 domicílios retirados da pesquisa *Survey of Consumer Finances (SCF)* aplicada em 2004 nos Estados Unidos da América, cujo objetivo é avaliar os valores de indenizações de seguros. A principal variável do estudo é a Renda, em que utilizando as variáveis auxiliares Gênero, Idade, Estado Civil, Anos de Escolaridade e Etnia, podemos inferir sobre a Renda dos entrevistados do banco de dados. O objetivo principal é realizar as inferências de dados faltantes pelos métodos de imputação múltipla através dos casos de perda completamente aleatória, perda aleatória e perda não aleatória. Os casos de perda completamente aleatória referem-se a probabilidade de dados ausentes não depender das variáveis do estudo, já os casos de perda aleatória ocorre quando a probabilidade de perda está relacionada com as variáveis do estudo mas não com a variável de interesse, que nesse estudo seria a Renda; e a perda não aleatória ocorre quando a probabilidade de perda está relacionada com a variável de interesse. Como o estudo está em andamento ainda não possui resultados significativos, entretanto através da análise descritiva percebemos que a Renda é influênciada pelas outras variáveis para o banco de dados utilizados. O principal a avaliar será como o método de imputação múltipla será eficiente para o banco de dados escolhido, e fazer as comparações dos valores imputados com os valores originais. Com essas comparações concluiremos sobre a utilização do método de imputação múltipla para banco de dados de pesquisas que possuem dados ausentes.